# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256"]
end

  config.vm.define "db-backup" do |db|
     db.vm.hostname = "db-backup.io"
     db.vm.box = "centos/7"
     db.vm.network :private_network, ip: "10.20.0.104"
  end 

end
