# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  # server Frontend, Backend and Database
  config.vm.define "frontend" do |app|
     app.vm.hostname = "frontend.io"
     app.vm.box = "centos/7"
     app.vm.network :private_network, ip: "10.20.0.101"
  end 

  config.vm.define "backend" do |app|
     app.vm.hostname = "backend.io"
     app.vm.box = "centos/7"
     app.vm.network :private_network, ip: "10.20.0.102"
  end 

  config.vm.define "database" do |db|
     db.vm.hostname = "database.io"
     db.vm.box = "centos/7"
     db.vm.network :private_network, ip: "10.20.0.103"
  end 


end
